import type { Metadata } from "next";

import "./globals.css";
import Navebar from "@/components/navbar";



export const metadata: Metadata = {
  title: "blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navebar/>
        {children}
      </body>
    </html>
  );
}
